{
  "description": "Should respond with internal server?? error because of invalid record in database results",
  "contextName": "bib",
  "isPrivileged": false,
  "alephLibrary": "foo00",
  "melindaPrefix": "FI-MELINDA",
  "requests": [
    {
      "method": "GET",
      "status": 500,
      "requestParams": {
        "verb": "GetRecord",
        "metadataPrefix": "marc21",
        "identifier": "oai:foo.bar/12345"
      }
    }
  ],
  "dbResults": [
    [
      {
        "TIME": "20000102050000",
        "ID": "12345",
        "RECORD": {
          "leader": "03106cam a2200721 i 4500",
          "fields": [
            {
              "tag": "001",
              "value": "12345"
            },
            {
              "tag": "245",
              "subfields": [
                {
                  "code": "a",
                  "value": "Foo Bar"
                }
              ]
            },
            {
              "tag": "699",
              "ind1": "1",
              "ind2": " "
            }
          ]
        }
      }
    ]
  ]
}
